apiVersion: mxp.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: production
  labels:
    platform: production
spec:
  writeConnectionSecretToRef:
    name: kubeconfig-production
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-platform
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-production
      key: kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-runtime
  namespace: flux-system
spec:
  dependsOn:
  - name: production-platform
  interval: 1m0s
  path: ./runtime/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-production
      key: kubeconfig
