apiVersion: mxp.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: staging
  labels:
    platform: staging
spec:
  writeConnectionSecretToRef:
    name: kubeconfig-staging
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-platform
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-staging
      key: kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-runtime
  namespace: flux-system
spec:
  dependsOn:
  - name: staging-platform
  interval: 1m0s
  path: ./runtime/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-staging
      key: kubeconfig
